# Generated by Django 4.2.6 on 2023-11-02 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[['MALE', 'MALE'], ['FEMALE', 'FEMALE']], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('dor', models.DateTimeField(auto_now=True)),
                ('Blood', models.CharField(choices=[['A-', 'A-'], ['A+', 'A+'], ['B-', 'B-'], ['B+', 'B+'], ['O-', 'O-'], ['O+', 'O+'], ['AB-', 'AB-'], ['AB+', 'AB+']], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.base')),
                ('salary', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
            bases=('school.base',),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.base')),
                ('class_no', models.CharField(max_length=10)),
                ('cgpa', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('section', models.CharField(max_length=10)),
            ],
            bases=('school.base',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='school.base')),
                ('subject', models.CharField(max_length=10)),
                ('salary', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
            bases=('school.base',),
        ),
    ]
