# Generated by Django 4.2.6 on 2023-11-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[['MALE', 'MALE'], ['FEMALE', 'FEMALE']], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('dor', models.DateTimeField(auto_now=True)),
                ('Blood', models.CharField(choices=[['A-', 'A-'], ['A+', 'A+'], ['B-', 'B-'], ['B+', 'B+'], ['O-', 'O-'], ['O+', 'O+'], ['AB-', 'AB-'], ['AB+', 'AB+']], max_length=5)),
                ('branch', models.CharField(choices=[['CSE', 'CSE'], ['ECE', 'ECE'], ['EEE', 'EEE'], ['CIVIL', 'CIVIL'], ['MECH', 'MECH'], ['ONLINE', 'ONLINE']], max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('salary', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('design', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[['MALE', 'MALE'], ['FEMALE', 'FEMALE']], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('dor', models.DateTimeField(auto_now=True)),
                ('Blood', models.CharField(choices=[['A-', 'A-'], ['A+', 'A+'], ['B-', 'B-'], ['B+', 'B+'], ['O-', 'O-'], ['O+', 'O+'], ['AB-', 'AB-'], ['AB+', 'AB+']], max_length=5)),
                ('branch', models.CharField(choices=[['CSE', 'CSE'], ['ECE', 'ECE'], ['EEE', 'EEE'], ['CIVIL', 'CIVIL'], ['MECH', 'MECH'], ['ONLINE', 'ONLINE']], max_length=10)),
                ('salary', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveBigIntegerField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[['MALE', 'MALE'], ['FEMALE', 'FEMALE']], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('dor', models.DateTimeField(auto_now=True)),
                ('Blood', models.CharField(choices=[['A-', 'A-'], ['A+', 'A+'], ['B-', 'B-'], ['B+', 'B+'], ['O-', 'O-'], ['O+', 'O+'], ['AB-', 'AB-'], ['AB+', 'AB+']], max_length=5)),
                ('branch', models.CharField(choices=[['CSE', 'CSE'], ['ECE', 'ECE'], ['EEE', 'EEE'], ['CIVIL', 'CIVIL'], ['MECH', 'MECH'], ['ONLINE', 'ONLINE']], max_length=10)),
                ('class_no', models.CharField(max_length=10)),
                ('cgpa', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
