# Generated by Django 4.2.6 on 2023-10-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('sid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('marks', models.PositiveIntegerField()),
            ],
        ),
    ]
