# Generated by Django 4.2.6 on 2023-10-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_model',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('series', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[['Red', 'RED'], ['Blue', 'BLUE'], ['White', 'WHITE'], ['Black', 'BLACK']], max_length=20)),
                ('valid', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('ins', models.BooleanField()),
                ('warranty', models.PositiveIntegerField()),
            ],
        ),
    ]
