# Generated by Django 4.2.6 on 2023-11-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penhome', '0002_car_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_model',
            fields=[
                ('subid', models.AutoField(primary_key=True, serialize=False)),
                ('science', models.BooleanField()),
                ('social', models.BooleanField()),
                ('maths', models.BooleanField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penhome.student_model')),
            ],
        ),
    ]
