# Generated by Django 4.2.6 on 2023-11-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('model_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='spec',
            fields=[
                ('laptop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='laptop.laptop')),
                ('rom', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('type_os', models.CharField(choices=[['WINDOWS', 'WINDOWS'], ['UNIX', 'UNIX'], ['MAC', 'MAC']], max_length=20)),
                ('desc', models.TextField()),
            ],
            bases=('laptop.laptop',),
        ),
    ]
